name: 'Automation Change ClickUp Ticket Status'
description: ''
inputs:
  clickUpTaskIdReg:  # id of input
    description: 'Javascript regular expression to detect task id'
    required: true
    default: 'BEIN-\d+'
  clickUpTeamId: # id of input
    description: 'ClickUp team Id'
    required: true
  clickUpToken: # id of input
    description: 'ClickUp Personal Access Token'
    required: true
  triggerPrefixes: # id of input
    description: 'List of PR prefixes will trigger automation status changing'
    default: 'DEV,STG,RLS,PRD'
    required: true
outputs:
  time: # id of output
    description: 'The time job finished'
runs:
  using: 'node16'
  main: 'index.js'